#!/bin/bash
clear
echo "=================================================="
echo "      FREEDOM ARCHITECT CONTROLLED AUTO MAP       "
echo "=================================================="
echo ""
echo "[MODE]"
cat "$HOME/FreedomArchitect/18_Controlled_Auto_Framework/config/controlled_auto.json"
echo ""
echo "--------------------------------------------------"
echo "[ROLE CHARTER]"
cat "$HOME/FreedomArchitect/18_Controlled_Auto_Framework/docs/MASTER_ROLE_CHARTER.md"
echo ""
echo "--------------------------------------------------"
echo "[MISSING UPGRADES]"
cat "$HOME/FreedomArchitect/18_Controlled_Auto_Framework/docs/WEAKNESS_AND_UPGRADES.md"
echo ""
echo "=================================================="
echo "Quick Files:"
echo "  charter    -> nano ~/FreedomArchitect/18_Controlled_Auto_Framework/docs/MASTER_ROLE_CHARTER.md"
echo "  alerts     -> nano ~/FreedomArchitect/18_Controlled_Auto_Framework/docs/ALERT_POLICY.md"
echo "  approval   -> nano ~/FreedomArchitect/18_Controlled_Auto_Framework/docs/APPROVAL_MATRIX.md"
echo "  sintra     -> nano ~/FreedomArchitect/18_Controlled_Auto_Framework/docs/SINTRA_DEPLOYMENT_COPY.md"
echo "=================================================="
