PLACEMENT={"github":"CODE_AUTHORITY","ledger":"FACTUAL_EVIDENCE_AUTHORITY","orchestra":"PLACEMENT_INTEGRATION_RELEASE_AUTHORITY","living_dashboard":"HUMAN_DIGITAL_TWIN","slack":"NON_AUTHORITATIVE_NOTIFICATION_SINK"}
def locate(name:str): return PLACEMENT.get(name,"UNREGISTERED")
